steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-f",
        "frontend/Dockerfile",
        "-t",
        "europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/bball-ai-ref-frontend:$COMMIT_SHA",
        ".",
      ]
images:
  - "europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/bball-ai-ref-frontend:$COMMIT_SHA"
options:
  logging: CLOUD_LOGGING_ONLY
