BBREF_CORS_ORIGINS: '["http://localhost:3000","https://<frontend-run-url>"]'
BBREF_GCP_PROJECT_ID: '<project-id-or-number>'
BBREF_GOOGLE_API_KEY_SECRET_ID: '<secret-name>'
BBREF_GOOGLE_API_KEY_SECRET_VERSION: 'latest'
